apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: orbi-exporter
  name: orbi-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orbi-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orbi-exporter
    spec:
      containers:
        - name: orbi-exporter
          envFrom:
            - configMapRef:
                name: orbi-exporter
            - secretRef:
                name: orbi-exporter
          image: ghcr.io/micktwomey/orbi_exporter:0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "100m"
