apiVersion: v1
kind: Service
metadata:
  name: orbi_exporter
  labels:
    app.kubernetes.io/name: orbi_exporter
spec:
  ports:
    - port: 8000
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: orbi_exporter
